import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { keyHint, keyText, rawKeyHint } from "@mariozechner/pi-coding-agent";
import { Text } from "@mariozechner/pi-tui";
import { Type } from "@sinclair/typebox";
import { JinhoFooter, type CacheStats, type ActiveTools } from "./footer.js";
import { homedir } from "os";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { discoverAgents } from "./agents.js";
import { runAgent, mapWithConcurrencyLimit, MAX_CONCURRENCY, MAX_PARALLEL_TASKS, resolveDepthConfig, getCycleViolations } from "./subagent.js";
import { emptyUsage, isResultError, isResultSuccess, getResultSummaryText, getFinalOutput, type SingleResult, type SubagentDetails } from "./types.js";
import { renderCall, renderResult } from "./render.js";
import { loadState, updateState } from "./state.js";
import { parsePlan } from "./plan-parser.js";
import { buildValidatorPrompt } from "./validator-template.js";
import { readFile, writeFile, mkdir } from "fs/promises";
import { microcompactMessages, getCompactionPrompt, formatCompactSummary } from "./compaction.js";
import { convertToLlm, serializeConversation } from "@mariozechner/pi-coding-agent";
import { complete } from "@mariozechner/pi-ai";
import { isDisciplineAgent, augmentAgentWithBoth, augmentAgentWithContext, IDS_RULES, getSlopCleanerTask } from "./discipline.js";
import { fetchUrlToMarkdown } from "./webfetch/utils.js";
import { renderWebfetchCall, renderWebfetchResult } from "./webfetch/render.js";

type WorkflowPhase =
  | "idle"
  | "clarifying"
  | "planning"
  | "ultraplanning";

let currentPhase: WorkflowPhase = "idle";
let activeGoalDocument: string | null = null;
let projectContext: string = "";

const STATE_FILE = join(homedir(), ".pi", "jinho-ids-state.json");

const cacheStats: CacheStats = { totalInput: 0, totalCacheRead: 0 };

const activeTools: ActiveTools = { running: new Map() };

async function findJinhoMd(startDir: string): Promise<string | null> {
  let dir = startDir;
  while (true) {
    const candidate = join(dir, "JINHO.md");
    try {
      await readFile(candidate, "utf-8");
      return candidate;
    } catch { /* not here */ }
    const parent = dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

export default function (pi: ExtensionAPI) {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const BUNDLED_AGENTS_DIR = join(__dirname, "agents");
  const BUNDLED_SKILLS_DIR = join(__dirname, "skills");

  const DIRECT_INPUT_OPTION = "직접 입력하기";

  const AskUserQuestionParams = Type.Object({
    question: Type.String({
      description: "The question to ask the user. The agent generates this dynamically based on context.",
    }),
    choices: Type.Optional(
      Type.Array(Type.String(), {
        description:
          "Multiple choice options generated by the agent. '직접 입력하기' is auto-appended. Omit for free-text input.",
      })
    ),
    placeholder: Type.Optional(
      Type.String({
        description: "Placeholder hint for free-text input mode.",
      })
    ),
    defaultValue: Type.Optional(
      Type.String({
        description: "Default value if user presses Enter without typing.",
      })
    ),
  });

  pi.registerTool({
    name: "ask_user_question",
    label: "Ask User Question",
    description:
      "Ask the user a question when the agent needs clarification. The agent composes the question and optional choices dynamically. Returns the user's answer as text.",
    promptSnippet:
      "Ask the user a clarifying question with optional multiple-choice answers",
    promptGuidelines: [
      "Use ask_user_question whenever you encounter ambiguity, unclear scope, or need user preference.",
      "Generate the question and choices yourself based on the current context — do not rely on predefined templates.",
      "Offer concrete choices (A/B/C style) when the options are enumerable. Omit choices for open-ended questions.",
      "Ask one focused question at a time. Do not bundle multiple questions.",
      "After receiving an answer, decide whether further clarification is needed or proceed with the task.",
    ],
    parameters: AskUserQuestionParams,
    execute: async (toolCallId, params, signal, onUpdate, ctx) => {
      const { question, choices, placeholder, defaultValue } = params;

      let answer: string | undefined;

      if (choices && choices.length > 0) {
        const withDirect = choices.includes(DIRECT_INPUT_OPTION)
          ? choices
          : [...choices, DIRECT_INPUT_OPTION];

        answer = await ctx.ui.select(question, withDirect, { signal });

        if (answer === DIRECT_INPUT_OPTION) {
          answer = await ctx.ui.input(question, placeholder || defaultValue, {
            signal,
          });
        }
      } else {
        answer = await ctx.ui.input(question, placeholder || defaultValue, {
          signal,
        });
      }

      if (answer === undefined) {
        return {
          content: [{ type: "text", text: "User cancelled the question." }],
          details: undefined,
        };
      }

      return {
        content: [{ type: "text", text: answer }],
        details: undefined,
      };
    },
  });

  const HEARTBEAT_MS = 1000;
  const depthConfig = resolveDepthConfig();

  const TaskItem = Type.Object({
    agent: Type.String({ description: "Name of the agent to invoke" }),
    task: Type.String({ description: "Task to delegate to the agent" }),
    cwd: Type.Optional(Type.String({ description: "Working directory for the agent process" })),
  });

  const ChainItem = Type.Object({
    agent: Type.String({ description: "Name of the agent to invoke" }),
    task: Type.String({ description: "Task with optional {previous} placeholder for prior step output" }),
    cwd: Type.Optional(Type.String({ description: "Working directory for the agent process" })),
  });

  const SubagentParams = Type.Object({
    agent: Type.Optional(Type.String({ description: "Agent name for single mode execution" })),
    task: Type.Optional(Type.String({ description: "Task description for single mode execution" })),
    tasks: Type.Optional(Type.Array(TaskItem, { description: "Array of {agent, task} objects for parallel execution (max 8)" })),
    chain: Type.Optional(Type.Array(ChainItem, { description: "Array of {agent, task} objects for sequential chaining. Use {previous} in task to reference prior output." })),
    agentScope: Type.Optional(Type.Unsafe<"user" | "project" | "both">({
      type: "string", enum: ["user", "project", "both"],
      description: 'Which agent directories to search. Default: "user".',
      default: "user",
    })),
    cwd: Type.Optional(Type.String({ description: "Working directory for single mode" })),
    planFile: Type.Optional(Type.String({ description: "Path to plan file. Required when agent is plan-validator — the validator prompt is built from this file, not from the task field." })),
    planTaskId: Type.Optional(Type.Number({ description: "Task number in the plan file to validate (e.g. 1 for Task 1). Required when agent is plan-validator." })),
  });

  const makeDetails = (mode: "single" | "parallel") => (results: SingleResult[]): SubagentDetails => ({ mode, results });

  if (depthConfig.canDelegate) {
    pi.registerTool({
      name: "subagent",
      label: "Subagent",
      description:
        "Delegate tasks to specialized agents running as separate pi processes. Supports single, parallel, and chain execution modes.",
      promptSnippet:
        "Delegate tasks to specialized agents (single, parallel, or chain mode)",
      promptGuidelines: [
        "Use single mode (agent + task) for one-off tasks. Use parallel mode (tasks array) for concurrent dispatch. Use chain mode (chain array) for sequential pipelines with {previous} placeholder.",
        "ONLY use these exact agent names — do NOT invent or guess agent names: explorer, worker, planner, plan-worker, plan-validator, plan-compliance, reviewer-feasibility, reviewer-architecture, reviewer-risk, reviewer-dependency, reviewer-user-value.",
        "All agents use the default model. Do NOT specify or mention specific models (no Haiku, Sonnet, etc.).",
        "For codebase exploration: use 'explorer'. For general execution: use 'worker'. For plan execution: use 'plan-compliance' → 'plan-worker' → 'plan-validator'.",
        "For ultraplan milestone reviews: dispatch all 5 reviewers in parallel: reviewer-feasibility, reviewer-architecture, reviewer-risk, reviewer-dependency, reviewer-user-value.",
        "Max 8 parallel tasks with 4 concurrent. Chain mode stops on first error.",
        "When calling plan-validator, ALWAYS provide planFile (path to the plan .md file) and planTaskId (the task number to validate). The validator prompt will be built from the plan file automatically — you do not need to compose it. Example: { agent: 'plan-validator', task: 'validate', planFile: 'docs/.../plan.md', planTaskId: 3 }",
      ],
      parameters: SubagentParams,

      renderCall: (args, theme) => renderCall(args, theme),
      renderResult: (result, { expanded }, theme) => renderResult(result, expanded, theme),

      execute: async (toolCallId, params, signal, onUpdate, ctx) => {
        const { agent, task, tasks, chain, agentScope, cwd } = params;
        const defaultCwd = ctx.cwd;
        const agents = await discoverAgents(defaultCwd, agentScope || "user", BUNDLED_AGENTS_DIR);
        const findAgent = (name: string) => agents.find((a) => a.name === name);

        // Safety: cycle detection
        if (depthConfig.preventCycles) {
          const requested: string[] = [];
          if (agent) requested.push(agent);
          if (tasks) for (const t of tasks) requested.push(t.agent);
          if (chain) for (const s of chain) requested.push(s.agent);
          const violations = getCycleViolations(requested, depthConfig.ancestorStack);
          if (violations.length > 0) {
            return {
              content: [{ type: "text" as const, text: `Blocked: delegation cycle detected. Agents already in stack: ${violations.join(", ")}. Stack: ${depthConfig.ancestorStack.join(" -> ") || "(root)"}` }],
              details: makeDetails("single")([]),
              isError: true,
            };
          }
        }

        if (chain && chain.length > 0) {
          let previousOutput = "";
          const allResults: SingleResult[] = [];

          for (let i = 0; i < chain.length; i++) {
            const step = chain[i];
            const taskWithContext = step.task.replace(/\{previous\}/g, previousOutput);
            const ctx_ = projectContext || IDS_RULES;
              const chainAgent = isDisciplineAgent(step.agent)
              ? augmentAgentWithBoth(findAgent(step.agent), ctx_)
              : augmentAgentWithContext(findAgent(step.agent), ctx_);
            const result = await runAgent({
              agent: chainAgent,
              agentName: step.agent,
              task: taskWithContext,
              cwd: step.cwd || defaultCwd,
              depthConfig,
              signal,
              onUpdate,
              makeDetails: makeDetails("single"),
            });
            allResults.push(result);

            if (isResultError(result)) {
              const summary = allResults.map((r, j) => `[${chain[j].agent}] ${isResultError(r) ? "failed" : "completed"}: ${getResultSummaryText(r)}`).join("\n\n");
              return {
                content: [{ type: "text" as const, text: `Chain failed at step ${i + 1}: ${result.errorMessage || "error"}\n\n${summary}` }],
                details: makeDetails("single")(allResults),
              };
            }
            previousOutput = getFinalOutput(result.messages) || result.stderr;
          }

          const summary = allResults.map((r, i) => `[${chain[i].agent}] completed: ${getResultSummaryText(r)}`).join("\n\n");
          return {
            content: [{ type: "text" as const, text: summary }],
            details: makeDetails("single")(allResults),
          };
        }

        if (tasks && tasks.length > 0) {
          if (tasks.length > MAX_PARALLEL_TASKS) {
            return {
              content: [{ type: "text" as const, text: `Too many parallel tasks (${tasks.length}). Max is ${MAX_PARALLEL_TASKS}.` }],
              details: makeDetails("parallel")([]),
            };
          }

          const allResults: SingleResult[] = tasks.map((t) => ({
            agent: t.agent, agentSource: "unknown" as const, task: t.task,
            exitCode: -1, messages: [], stderr: "", usage: emptyUsage(),
          }));

          const emitProgress = () => {
            if (!onUpdate) return;
            const done = allResults.filter((r) => r.exitCode !== -1).length;
            const running = allResults.filter((r) => r.exitCode === -1).length;
            onUpdate({
              content: [{ type: "text" as const, text: `Parallel: ${done}/${allResults.length} done, ${running} running...` }],
              details: makeDetails("parallel")([...allResults]),
            });
          };

          let heartbeat: ReturnType<typeof setInterval> | undefined;
          if (onUpdate) {
            emitProgress();
            heartbeat = setInterval(() => {
              if (allResults.some((r) => r.exitCode === -1)) emitProgress();
            }, HEARTBEAT_MS);
          }

          let results: SingleResult[];
          try {
            results = await mapWithConcurrencyLimit(tasks, MAX_CONCURRENCY, async (t, index) => {
              const pCtx = projectContext || IDS_RULES;
              const parallelAgent = isDisciplineAgent(t.agent)
                ? augmentAgentWithBoth(findAgent(t.agent), pCtx)
                : augmentAgentWithContext(findAgent(t.agent), pCtx);
              const result = await runAgent({
                agent: parallelAgent,
                agentName: t.agent,
                task: t.task,
                cwd: t.cwd || defaultCwd,
                depthConfig,
                signal,
                onUpdate: (partial) => {
                  if (partial.details?.results[0]) {
                    allResults[index] = partial.details.results[0];
                    emitProgress();
                  }
                },
                makeDetails: makeDetails("parallel"),
              });
              allResults[index] = result;
              emitProgress();
              return result;
            });
          } finally {
            if (heartbeat) clearInterval(heartbeat);
          }

          const successCount = results.filter((r) => isResultSuccess(r)).length;
          const summaries = results.map((r) =>
            `[${r.agent}] ${isResultError(r) ? "failed" : "completed"}: ${getResultSummaryText(r)}`,
          );
          return {
            content: [{ type: "text" as const, text: `Parallel: ${successCount}/${results.length} succeeded\n\n${summaries.join("\n\n")}` }],
            details: makeDetails("parallel")(results),
          };
        }

        if (agent && task) {
          let effectiveTask = task;

          // Validator information barrier: replace LLM-composed task with
          // code-generated prompt built directly from the plan file.
          if (agent === "plan-validator" && params.planFile && params.planTaskId != null) {
            try {
              const planContent = await readFile(params.planFile, "utf-8");
              const parsed = parsePlan(planContent);
              const planTask = parsed.tasks.find((t) => t.id === params.planTaskId);
              if (planTask) {
                effectiveTask = buildValidatorPrompt(planTask, parsed.verificationCommand);
              }
            } catch {
            }
          }

          const sCtx = projectContext || IDS_RULES;
          const singleAgent = isDisciplineAgent(agent)
            ? augmentAgentWithBoth(findAgent(agent), sCtx)
            : augmentAgentWithContext(findAgent(agent), sCtx);
          const result = await runAgent({
            agent: singleAgent,
            agentName: agent,
            task: effectiveTask,
            cwd: cwd || defaultCwd,
            depthConfig,
            signal,
            onUpdate,
            makeDetails: makeDetails("single"),
          });

          if (isDisciplineAgent(agent) && isResultSuccess(result)) {
            const slopCleaner = findAgent("slop-cleaner");
            if (slopCleaner) {
              const cleanResult = await runAgent({
                agent: slopCleaner,
                agentName: "slop-cleaner",
                task: getSlopCleanerTask(),
                cwd: cwd || defaultCwd,
                depthConfig,
                signal,
                onUpdate,
                makeDetails: makeDetails("single"),
              });
              const mainText = getResultSummaryText(result);
              const cleanText = isResultSuccess(cleanResult)
                ? `\n\n[slop-cleaner] completed: ${getResultSummaryText(cleanResult)}`
                : `\n\n[slop-cleaner] failed: ${getResultSummaryText(cleanResult)}`;
              return {
                content: [{ type: "text" as const, text: mainText + cleanText }],
                details: makeDetails("single")([result, cleanResult]),
              };
            }
          }

          if (isResultError(result)) {
            return {
              content: [{ type: "text" as const, text: `Agent ${result.stopReason || "failed"}: ${getResultSummaryText(result)}` }],
              details: makeDetails("single")([result]),
              isError: true,
            };
          }
          return {
            content: [{ type: "text" as const, text: getResultSummaryText(result) }],
            details: makeDetails("single")([result]),
          };
        }

        return {
          content: [{ type: "text" as const, text: "Error: Specify either (agent + task) for single mode, tasks for parallel mode, or chain for chain mode." }],
          details: makeDetails("single")([]),
        };
      },
    });
  }

  const WebFetchParams = Type.Object({
    url: Type.String({
      description: "The URL to fetch and convert to Markdown",
    }),
    raw: Type.Optional(
      Type.Boolean({
        description:
          "Convert the full HTML page to Markdown without filtering",
        default: false,
      }),
    ),
    includeScripts: Type.Optional(
      Type.Boolean({
        description:
          "Include <script> and <style> tag content in the output. Default: false (stripped)",
        default: false,
      }),
    ),
    maxLength: Type.Optional(
      Type.Number({
        description:
          "Maximum number of characters to return. Content beyond this limit is truncated.",
      }),
    ),
  });

  pi.registerTool({
    name: "webfetch",
    label: "WebFetch",
    description:
      "Fetch a URL and convert its HTML content to clean Markdown. Uses Turndown + GFM for Markdown conversion. Results are cached for 15 minutes.",
    promptSnippet: "Fetch a URL and convert to Markdown",
    promptGuidelines: [
      "Use webfetch to retrieve and read web pages, documentation, or any URL content.",
      "Script and style tags are stripped by default. Use includeScripts: true when you need CSS/JS source code.",
      "Use raw: true when you need the full HTML page converted without any filtering.",
      "Use maxLength to limit output size for very large pages.",
      "Results are cached for 15 minutes — repeated requests for the same URL return instantly.",
    ],
    parameters: WebFetchParams,

    renderCall: (args, theme) => renderWebfetchCall(args, theme),
    renderResult: (result, { expanded }, theme) =>
      renderWebfetchResult(result, expanded, theme),

    execute: async (toolCallId, params, signal, _onUpdate, _ctx) => {
      const { url, raw, maxLength, includeScripts } = params;
      try {
        const { content, details } = await fetchUrlToMarkdown(url, {
          raw,
          maxLength,
          includeScripts,
          signal,
        });
        return {
          content: [{ type: "text" as const, text: content }],
          details,
        };
      } catch (err) {
        const message =
          err instanceof Error ? err.message : String(err);
        return {
          content: [
            {
              type: "text" as const,
              text: `Error fetching ${url}: ${message}`,
            },
          ],
          details: undefined,
          isError: true,
        };
      }
    },
  });

  pi.on("resources_discover", async (_event, _ctx) => {
    return {
      skillPaths: [BUNDLED_SKILLS_DIR],
    };
  });

  const IDS_CONTEXT_BRIEF = [
    "\n\n## IDS Project Context",
    "Project: IDS (Intelligent Deployment System) — AI-driven cloud resource prediction & auto-deployment on Aolda (Ajou OpenStack).",
    "Stack: Python 3.11, FastAPI, TensorFlow LSTM, MySQL+SQLAlchemy 2.0, Pydantic v2.",
    "Architecture: 4-layer DDD per service — application/ → domain/ → ports/ → infrastructure/",
    "Services: planning (plan generation), prediction (LSTM 24h forecast), deployment (OpenStack VM), alerting (Discord).",
    "Current phase: Phase 0 MVP (4/20) — most service files are TODO stubs referencing mcp_core/ originals.",
    "Docs live in: docs/adr/, docs/architecture/, docs/runbook/, docs/api/",
  ].join("\n");

  const PHASE_GUIDANCE: Record<WorkflowPhase, string> = {
    idle: "",
    clarifying: [
      "\n\n## Active Workflow: Clarification (IDS)",
      "You are in agentic-clarification mode. Follow the agentic-clarification skill rules strictly:",
      "- Ask ONE question per message using the ask_user_question tool.",
      "- Generate questions and choices dynamically — consider IDS domain boundaries (planning/prediction/deployment/alerting).",
      "- Use the subagent tool with agent 'explorer' to investigate the IDS codebase in parallel.",
      "  - Look in services/<domain>/domain/ for existing entities and policies.",
      "  - Look in services/<domain>/ports/ to understand current interface contracts.",
      "  - Check TODO comments for migration references from mcp_core/.",
      "- After each answer, update 'what we've established so far' and assess remaining ambiguity.",
      "- When ambiguity is resolved, present a Context Brief that includes: affected IDS domain(s), layer impact (application/domain/ports/infrastructure), Phase 0 or Phase 1 scope.",
      "- Do NOT start implementation. This phase ends with a Context Brief, not code.",
    ].join("\n"),
    planning: [
      "\n\n## Active Workflow: Plan Crafting (IDS)",
      "You are in agentic-plan-crafting mode. Follow the agentic-plan-crafting skill rules strictly:",
      "- Write an executable implementation plan from the current context.",
      "- Every step must be executable — no placeholders like 'implement the service'.",
      "- For each step, identify: which layer (application/domain/ports/infrastructure), which service domain, which files.",
      "- Respect layer rules: domain/ must stay pure (no I/O), ports/ changes require all infrastructure/ implementations updated.",
      "- If migrating from mcp_core/, note the source file path and what must change.",
      "- Use ask_user_question if you need to resolve any remaining ambiguity.",
      "- End with a Self-Review before presenting the plan.",
    ].join("\n"),
    ultraplanning: [
      "\n\n## Active Workflow: Milestone Planning — Ultraplan (IDS)",
      "You are in agentic-milestone-planning mode. Follow the agentic-milestone-planning skill rules strictly:",
      "- Compose a Problem Brief from the current context.",
      "- Frame milestones around IDS service domains and development phases (Phase 0 Critical → Phase 1 High).",
      "- Dispatch all 5 reviewer agents in parallel: reviewer-feasibility, reviewer-architecture, reviewer-risk, reviewer-dependency, reviewer-user-value.",
      "- reviewer-architecture must validate 4-layer DDD compliance in each milestone.",
      "- reviewer-risk must flag any OpenStack integration risk or ML model assumption risk.",
      "- Synthesize all reviewer findings into a milestone DAG.",
      "- Use ask_user_question if you need user input on trade-offs.",
    ].join("\n"),
  };

  pi.on("before_agent_start", async (event, _ctx) => {
    const guidance = PHASE_GUIDANCE[currentPhase];
    const contextBlock = projectContext
      ? `\n\n## Project Context (JINHO.md)\n${projectContext}`
      : IDS_CONTEXT_BRIEF;

    let delegationInfo = "";
    if (depthConfig.canDelegate) {
      const agentList = (await discoverAgents(_ctx.cwd || ".", "user", BUNDLED_AGENTS_DIR))
        .map((a) => `- **${a.name}**: ${a.description}`)
        .join("\n");
      delegationInfo = `\n\n## Delegation Guards\n- Current depth: ${depthConfig.currentDepth}, max: ${depthConfig.maxDepth}\n- Cycle prevention: ${depthConfig.preventCycles ? "enabled" : "disabled"}\n- Ancestor stack: ${depthConfig.ancestorStack.length > 0 ? depthConfig.ancestorStack.join(" -> ") : "(root)"}\n\n## Available Subagents\n${agentList}`;
    }

    return {
      systemPrompt: event.systemPrompt + contextBlock + (guidance || "") + delegationInfo,
    };
  });

  pi.on("context", async (event, _ctx) => {
    const compacted = microcompactMessages(event.messages);
    const changed = compacted.some((msg, i) => msg !== event.messages[i]);
    if (!changed) return;
    return { messages: compacted };
  });

  pi.on("session_before_compact", async (event, ctx) => {
    // Skip custom compaction for idle phase with no active goal document —
    // let pi's default compaction handle simple conversations.
    if (currentPhase === "idle" && !activeGoalDocument) return;

    const { preparation, signal } = event;
    const { messagesToSummarize, turnPrefixMessages, tokensBefore, firstKeptEntryId, previousSummary } = preparation;

    const model = ctx.model;
    if (!model) {
      ctx.ui.notify("No model available, using default compaction", "warning");
      return;
    }
    const auth = await ctx.modelRegistry.getApiKeyAndHeaders(model);
    if (!auth.ok || !auth.apiKey) {
      ctx.ui.notify("Compaction auth failed, using default compaction", "warning");
      return;
    }

    const allMessages = [...messagesToSummarize, ...turnPrefixMessages];
    if (allMessages.length === 0) return;

    ctx.ui.notify(
      `Custom compaction: summarizing ${allMessages.length} messages (${tokensBefore.toLocaleString()} tokens)...`,
      "info",
    );

    const conversationText = serializeConversation(convertToLlm(allMessages));

    const promptText = getCompactionPrompt(
      currentPhase,
      activeGoalDocument,
      event.customInstructions,
    );

    const previousContext = previousSummary
      ? `\n\nPrevious session summary for context:\n${previousSummary}`
      : "";

    const summaryMessages = [
      {
        role: "user" as const,
        content: [
          {
            type: "text" as const,
            text: `${promptText}${previousContext}\n\n<conversation>\n${conversationText}\n</conversation>`,
          },
        ],
        timestamp: Date.now(),
      },
    ];

    try {
      const response = await complete(
        model,
        { messages: summaryMessages },
        {
          apiKey: auth.apiKey,
          headers: auth.headers,
          maxTokens: 8192,
          signal,
        },
      );

      const summary = response.content
        .filter((c): c is { type: "text"; text: string } => c.type === "text")
        .map((c) => c.text)
        .join("\n");

      if (!summary.trim()) {
        if (!signal.aborted) {
          ctx.ui.notify("Compaction summary was empty, using default", "warning");
        }
        return;
      }

      const formattedSummary = formatCompactSummary(summary);

      return {
        compaction: {
          summary: formattedSummary,
          firstKeptEntryId,
          tokensBefore,
          details: {
            phase: currentPhase,
            activeGoalDocument,
          },
        },
      };
    } catch (error) {
      if (signal.aborted) return;
      const message = error instanceof Error ? error.message : String(error);
      ctx.ui.notify(`Compaction failed: ${message}`, "error");
      return;
    }
  });

  pi.on("session_compact", async (event, _ctx) => {
    if (event.fromExtension && event.compactionEntry.details) {
      const details = event.compactionEntry.details as {
        phase?: string;
        activeGoalDocument?: string | null;
      };
      if (details.phase) currentPhase = details.phase as WorkflowPhase;
      if (details.activeGoalDocument !== undefined) {
        activeGoalDocument = details.activeGoalDocument;
      }
    }
  });

  const GOAL_DOC_PATTERN = /^docs\/(adr|architecture|runbook|api)\//;

  pi.on("tool_result", async (event, _ctx) => {
    if (currentPhase === "idle") return;

    const toolName = event.toolName;
    if (toolName !== "write" && toolName !== "edit") return;

    const filePath = event.input.path as string | undefined;
    if (!filePath) return;

    const relativePath = filePath.replace(/^.*?docs\//, "docs/");
    if (GOAL_DOC_PATTERN.test(relativePath)) {
      activeGoalDocument = relativePath;
      updateState(STATE_FILE, { activeGoalDocument: relativePath }).catch(() => {});
    }
  });

  pi.registerCommand("clarify", {
    description:
      "Start agentic-clarification — the agent asks dynamic questions to resolve ambiguity",
    handler: async (args, ctx) => {
      const topic = args?.trim() || "";
      const start = await ctx.ui.confirm(
        "Start Clarification",
        "The agent will ask you questions one at a time to clarify your request.\nIt will also explore the codebase in parallel.\n\nProceed?"
      );
      if (!start) return;

      currentPhase = "clarifying";
      activeGoalDocument = null;
      updateState(STATE_FILE, { phase: "clarifying", activeGoalDocument: null }).catch(() => {});
      ctx.ui.setStatus("JINHO", "Clarification in progress...");

      const prompt = topic
        ? `The user wants to clarify the following IDS task: "${topic}"\n\nBegin the agentic-clarification process for IDS. Follow the agentic-clarification skill rules.\n- Ask ONE question using the ask_user_question tool.\n- Use the subagent tool with agent 'explorer' to investigate the relevant IDS service domain in parallel (check services/<domain>/domain/, ports/, and TODO stubs).\n- Determine which phase (0/1/2) this belongs to and which layers are affected.`
        : `The user wants to start an agentic-clarification session for their current IDS task.\n\nBegin the agentic-clarification process for IDS. Follow the agentic-clarification skill rules.\n- Ask ONE question using the ask_user_question tool to understand what the user wants to accomplish.\n- Use the subagent tool with agent 'explorer' to investigate the IDS codebase in parallel (services/, libs/, ml/, docs/).\n- Determine which service domain (planning/prediction/deployment/alerting) and which layer (application/domain/ports/infrastructure) is involved.`;

      pi.sendUserMessage(prompt);
    },
  });

  pi.registerCommand("plan", {
    description:
      "Generate an implementation plan — the agent follows agentic-plan-crafting skill rules",
    handler: async (args, ctx) => {
      const ok = await ctx.ui.confirm(
        "Start Agentic Plan Crafting",
        "The agent will create an executable implementation plan based on current context using the agentic-plan-crafting workflow.\n\nProceed?"
      );
      if (!ok) return;

      currentPhase = "planning";
      updateState(STATE_FILE, { phase: "planning" }).catch(() => {});
      ctx.ui.setStatus("JINHO", "Agentic planning workflow in progress...");

      const topic = args?.trim() || "";
      const prompt = topic
        ? `Create an executable IDS implementation plan for: "${topic}"\n\nFollow the agentic-plan-crafting skill rules.\n- If a Context Brief exists from a previous /clarify, use it as input.\n- Each step must specify: file path, layer (application/domain/ports/infrastructure), service domain.\n- Flag any port interface changes — those require updating all infrastructure/ implementations.\n- Note any TODO stubs from mcp_core/ that this plan migrates.\n- Assign each step to Phase 0 (4/20 MVP) or Phase 1 (5/15).`
        : `Create an executable IDS implementation plan for the current task.\n\nFollow the agentic-plan-crafting skill rules.\n- If a Context Brief exists from a previous /clarify, use it as input.\n- If not, use ask_user_question to confirm: which service domain, which layer, Phase 0 or Phase 1.\n- Each step must be concrete — no 'implement the service' placeholders.\n- Respect 4-layer DDD: domain/ stays pure, ports/ changes cascade to infrastructure/.`;

      pi.sendUserMessage(prompt);
    },
  });

  pi.registerCommand("ultraplan", {
    description:
      "Decompose a complex task into milestones — the agent dynamically selects reviewers",
    handler: async (args, ctx) => {
      const confirmed = await ctx.ui.confirm(
        "Start Agentic Milestone Planning (Ultraplan)",
        "The agent will:\n1. Compose a Problem Brief\n2. Decide which reviewer perspectives are needed\n3. Dispatch reviewers in parallel\n4. Synthesize a milestone DAG\n\nProceed?"
      );
      if (!confirmed) return;

      currentPhase = "ultraplanning";
      updateState(STATE_FILE, { phase: "ultraplanning" }).catch(() => {});
      ctx.ui.setStatus("JINHO", "Agentic milestone workflow in progress...");

      const topic = args?.trim() || "";
      const prompt = topic
        ? `Decompose the following IDS task into milestones: "${topic}"\n\nFollow the agentic-milestone-planning skill rules.\n1. Compose a Problem Brief — identify which IDS service domains are affected and what the Phase 0/1/2 boundary is.\n2. Dispatch all 5 reviewer agents in parallel: reviewer-feasibility, reviewer-architecture, reviewer-risk, reviewer-dependency, reviewer-user-value.\n   - reviewer-architecture: validate 4-layer DDD compliance per milestone.\n   - reviewer-risk: flag OpenStack integration risk and ML model assumption risk.\n3. Synthesize findings into a milestone DAG aligned with IDS phases.`
        : `Decompose the current IDS task into milestones.\n\nFollow the agentic-milestone-planning skill rules.\n1. Compose a Problem Brief — identify which IDS service domains (planning/prediction/deployment/alerting) are involved and what Phase (0/1/2) the work targets.\n2. Dispatch all 5 reviewer agents in parallel: reviewer-feasibility, reviewer-architecture, reviewer-risk, reviewer-dependency, reviewer-user-value.\n3. Synthesize their findings into a milestone DAG aligned with IDS development phases.`;

      pi.sendUserMessage(prompt);
    },
  });

  pi.registerCommand("ask", {
    description: "Manual smoke test for the ask_user_question tool",
    handler: async (args, ctx) => {
      const topic = args?.trim() || "Ask me one focused question using the ask_user_question tool.";
      const confirmed = await ctx.ui.confirm(
        "Run /ask",
        "The agent will send a manual prompt that requires one ask_user_question tool call.\n\nProceed?"
      );
      if (!confirmed) return;

      currentPhase = "idle";
      ctx.ui.setStatus("JINHO", "Manual ask_user_question test in progress...");

      pi.sendUserMessage(
        `Manual tool test: use the ask_user_question tool exactly once, then stop. User context: "${topic}"`
      );
    },
  });

  const setupHandler = async (_args: string, ctx: any) => {
    const settingsPath = join(homedir(), ".pi", "agent", "settings.json");

    let current: Record<string, unknown> = {};
    try {
      const raw = await readFile(settingsPath, "utf-8");
      current = JSON.parse(raw);
    } catch {
    }

    if (current.quietStartup === true) {
      ctx.ui.notify("Settings already configured — quietStartup is true.", "info");
      return;
    }

    const ok = await ctx.ui.confirm(
      "Setup: Configure Recommended Settings",
      [
        "This will add \"quietStartup\": true to your settings.json:",
        `  ${settingsPath}`,
        "",
        "This hides the default Skills/Extensions/Themes listing at startup.",
        "The JINHO banner takes over instead.",
        "",
        "Proceed?",
      ].join("\n"),
    );
    if (!ok) return;

    const updated = { ...current, quietStartup: true };
    await mkdir(dirname(settingsPath), { recursive: true });
    await writeFile(settingsPath, JSON.stringify(updated, null, 2) + "\n");

    ctx.ui.notify("Settings updated — quietStartup is now true. Restart pi to see the effect.", "info");
  };

  pi.registerCommand("init", {
    description:
      "Configure recommended settings — sets quietStartup: true in ~/.pi/agent/settings.json",
    handler: setupHandler,
  });

  pi.registerCommand("setup", {
    description:
      "Configure recommended settings — sets quietStartup: true in ~/.pi/agent/settings.json",
    handler: setupHandler,
  });

  pi.registerCommand("ids-phase", {
    description: "Show IDS development phase status and what's TODO in Phase 0 / Phase 1",
    handler: async (_args, ctx) => {
      ctx.ui.setStatus("JINHO", "Checking IDS phase status...");
      pi.sendUserMessage(
        `Summarize the current IDS development phase status by reading the codebase.\n\n` +
        `1. Use the subagent tool with agent 'explorer' to scan for TODO stubs in services/ — count how many files per domain (planning/prediction/deployment/alerting) still have # TODO.\n` +
        `2. Report Phase 0 (MVP 4/20) critical items (C-1~C-5) completion status based on file content.\n` +
        `3. List what's done vs. still TODO per service domain.\n` +
        `4. Estimate Phase 0 readiness as a percentage.\n\n` +
        `Format as a concise status table.`
      );
    },
  });

  pi.registerCommand("reset-phase", {
    description: "Reset the workflow phase to idle (clears clarify/plan/ultraplan mode)",
    handler: async (_args, ctx) => {
      currentPhase = "idle";
      activeGoalDocument = null;
      updateState(STATE_FILE, { phase: "idle", activeGoalDocument: null }).catch(() => {});
      ctx.ui.setStatus("JINHO", undefined);
      ctx.ui.notify("Workflow phase reset to idle.", "info");
    },
  });

  pi.on("message_end", async (event, _ctx) => {
    const msg = event.message;
    if (msg.role === "assistant") {
      const usage = msg.usage;
      if (usage) {
        cacheStats.totalInput += usage.input;
        cacheStats.totalCacheRead += usage.cacheRead;
      }
    }
  });

  pi.on("tool_execution_start", async (event, _ctx) => {
    activeTools.running.set(event.toolCallId, event.toolName);
  });

  pi.on("tool_execution_end", async (event, _ctx) => {
    activeTools.running.delete(event.toolCallId);
  });

  pi.on("session_start", async (_event, ctx) => {
    const saved = await loadState(STATE_FILE);
    currentPhase = saved.phase;
    activeGoalDocument = saved.activeGoalDocument;

    cacheStats.totalInput = 0;
    cacheStats.totalCacheRead = 0;
    activeTools.running.clear();

    // Load project context from JINHO.md (walk up from cwd)
    try {
      const jinhoPath = await findJinhoMd(ctx.cwd);
      if (jinhoPath) {
        projectContext = await readFile(jinhoPath, "utf-8");
        ctx.ui.notify(`JINHO.md loaded — project context active (${jinhoPath})`, "info");
      } else {
        projectContext = "";
      }
    } catch {
      projectContext = "";
    }

    ctx.ui.setHeader((_tui, theme) => {
      const banner = [
        "     ██╗██╗███╗   ██╗██╗  ██╗ ██████╗ ",
        "     ██║██║████╗  ██║██║  ██║██╔═══██╗",
        "     ██║██║██╔██╗ ██║███████║██║   ██║",
        "██   ██║██║██║╚██╗██║██╔══██║██║   ██║",
        "╚█████╔╝██║██║ ╚████║██║  ██║╚██████╔╝",
        " ╚════╝ ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝ ╚═════╝ ",
      ].map(line => theme.bold(theme.fg("accent", line))).join("\n");

      const tagline = theme.fg("dim", "IDS — Intelligent Deployment System");

      const tips = [
        "Use /plan to generate a structured implementation plan after clarifying.",
        "Use /ultraplan for complex tasks that need multi-agent review.",
        "Use /reset-phase if you want to switch from one workflow to another.",
      ];
      const randomTip = tips[Math.floor(Math.random() * tips.length)];
      const tipLine = theme.fg("muted", `Tip: ${randomTip}`);
      const clarifyLine = theme.fg("dim", "However, in most cases, it's best to start with /clarify.");

      const hints = [
        keyHint("app.interrupt", "to interrupt"),
        keyHint("app.clear", "to clear"),
        rawKeyHint(`${keyText("app.clear")} twice`, "to exit"),
        keyHint("app.tools.expand", "to expand tools"),
        rawKeyHint("/", "for commands"),
        rawKeyHint("!", "to run bash"),
      ].join("\n");

      return new Text(`\n${banner}\n${tagline}\n\n${tipLine}\n${clarifyLine}\n\n${hints}`, 1, 0);
    });

    ctx.ui.setFooter((_tui, theme, footerData) => {
      return new JinhoFooter(theme, footerData, {
        cwd: ctx.cwd,
        getModelName: () => ctx.model?.name,
        getContextUsage: () => ctx.getContextUsage(),
      }, cacheStats, activeTools);
    });

    ctx.ui.notify(
      "JINHO Harness (IDS) loaded: /clarify, /plan, /ultraplan, /ids-phase, /reset-phase",
      "info"
    );
  });
}
